Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"

  config.vm.synced_folder "C:\\SF\\B10\\sf_practice\\6", "/vagrant_data"
  
  config.vm.provision "shell", inline: <<-SHELL
  sudo -s
  mkdir /var/shared
  cp /vagrant_data/empty.file /var/shared/empty.file
  apt-get update
  apt-get install -y python3
  apt-get install -y python3-pip
  apt-get install -y libpq-dev
  sudo -H pip3 install psycopg2
  sudo -H pip3 install django
    SHELL
  end
end